In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("words.csv", index_col="value")

In [3]:
df.head()

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
value,,,,,,,,,,,,,,,
46134,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8187,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8866,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
Index: 23220 entries, 46134 to 976077
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   year                  23220 non-null  int64
 1   industry_code_ANZSIC  23220 non-null  str
 2   industry_name_ANZSIC  23220 non-null  str
 3   rme_size_grp          23220 non-null  str
 4   variable              23220 non-null  str
 5   unit                  23220 non-null  str
 6   Unnamed: 7            0 non-null      float64
 7   Unnamed: 8            0 non-null      float64
 8   Unnamed: 9            41 non-null     float64
 9   Unnamed: 10           43 non-null     str
 10  Unnamed: 11           41 non-null     str
 11  Unnamed: 12           41 non-null     str
 12  Unnamed: 13           41 non-null     str
 13  Unnamed: 14           41 non-null     str
 14  Unnamed: 15           41 non-null     str
dtypes: float64(3), int64(1), str(11)
memory usage: 2.8+ MB

In [5]:
df.shape

(23220, 15)

In [8]:
df.head()

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
value,,,,,,,,,,,,,,,
46134,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8187,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8866,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df['variable'].max()

'Total income'

In [10]:
df.max()

year                                                       2025
industry_code_ANZSIC                                        all
industry_name_ANZSIC                            Wholesale Trade
rme_size_grp                                      j_Grand_Total
variable                                           Total income
unit                                          DOLLARS(millions)
Unnamed: 7                                                  NaN
Unnamed: 8                                                  NaN
Unnamed: 9                                               2023.0
Unnamed: 10                                                   R
Unnamed: 11             Rental, Hiring and Real Estate Services
Unnamed: 12                                    i_Industry_Total
Unnamed: 13                                        Total income
Unnamed: 14                                                   C
Unnamed: 15                                   DOLLARS(millions)
dtype: object

In [11]:
df.describe()

               year  Unnamed: 7  Unnamed: 8   Unnamed: 9
count  23220.000000         0.0         0.0    41.000000
mean    2018.000000         NaN         NaN  2022.268293
std        4.320587         NaN         NaN     0.448575
min     2011.000000         NaN         NaN  2022.000000
25%     2014.000000         NaN         NaN  2022.000000
50%     2018.000000         NaN         NaN  2022.000000
75%     2022.000000         NaN         NaN  2023.000000
max     2025.000000         NaN         NaN  2023.000000

In [12]:
df.loc[[
    "Activity unit",
    "Total assets"]]

KeyError: "None of [Index(['Activity unit', 'Total assets'], dtype='str', name='value')] are in the [index]"